name: Build and Release

on:
  push:
    tags:
      - 'v*' # Dispara quando tu crias uma tag (ex: v1.0.0)

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package

      - name: Install WiX Toolset
        run: dotnet tool install --global wix

      - name: Generate EXE with jpackage
        run: |
          jpackage --name "RMSH-TaskManager" `
                   --input target/ `
                   --main-jar RMSH-TaskTracker-1.0-SNAPSHOT.jar `
                   --type exe `
                   --win-shortcut `
                   --win-menu `
                   --dest output/

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: output/*.exe

  create-release:
    needs: build-windows
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            windows-exe/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}